// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1F4k7pYd7RF-6tLIWBNiMPgtS8ogDScc',
    appId: '1:269208703301:web:af0ab6f2bf1a08325b6e2c',
    messagingSenderId: '269208703301',
    projectId: 'flutter-chat-app-55271',
    authDomain: 'flutter-chat-app-55271.firebaseapp.com',
    databaseURL: 'https://flutter-chat-app-55271-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-app-55271.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB838s5eLFkLo-k3Kob-luD-PT1-9Fr4Ng',
    appId: '1:269208703301:android:54a55f0d7ce084ff5b6e2c',
    messagingSenderId: '269208703301',
    projectId: 'flutter-chat-app-55271',
    databaseURL: 'https://flutter-chat-app-55271-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-app-55271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvYVW_qVsuY9gdJhV-R32ye5n9rI34GcE',
    appId: '1:269208703301:ios:60b1dbe77b790fe25b6e2c',
    messagingSenderId: '269208703301',
    projectId: 'flutter-chat-app-55271',
    databaseURL: 'https://flutter-chat-app-55271-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-app-55271.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
